# Specifies the JVM arguments used for the daemon process.
# The setting is particularly useful for tweaking memory settings.
org.gradle.jvmargs=-Xmx1536m

# TODO double check if we need these for the SDK
#android.useAndroidX=true
#android.enableJetifier=true
#kotlin.code.style=official

VERSION_NAME=0.1.1-alpha09

# gradle-maven-publish configuration
GROUP=com.wire
SONATYPE_HOST=CENTRAL_PORTAL
SONATYPE_AUTOMATIC_RELEASE=true
RELEASE_SIGNING_ENABLED=true
POM_NAME=Cells API v2 SDK for KMP
POM_DESCRIPTION=Generated SDK to communicate with a Cells Server using the API v2 (for Cells v5+)
POM_INCEPTION_YEAR=2025
POM_URL=https://github.com/wireapp/cells-sdk-kmp
POM_LICENCE_NAME=The Apache Software License, Version 2.0
POM_LICENCE_URL=http://www.apache.org/licenses/LICENSE-2.0.txt
POM_LICENSE_DIST=repo
POM_SCM_URL=https://github.com/wireapp/cells-sdk-kmp
POM_SCM_CONNECTION=scm:git:github.com/wireapp/cells-sdk-kmp.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://github.com/wireapp/cells-sdk-kmp.git
POM_DEVELOPER_NAME=Bruno Sinou
POM_DEVELOPER_EMAIL=bruno.sinou@wire.com