/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.wire.kalium.cells.sdk.kmp.model


import kotlinx.serialization.*

/**
 * 
 *
 * Values: BaseObject,Activity,Link,Mention,Collection,OrderedCollection,CollectionPage,OrderedCollectionPage,Application,Group,Organization,Person,Service,Article,Audio,Document,Event,Image,Note,Page,Place,Profile,Relationship,Tombstone,Video,Accept,Add,Announce,Arrive,Block,Create,Delete,Dislike,Flag,Follow,Ignore,Invite,Join,Leave,Like,Listen,Move,Offer,Question,Reject,Read,Remove,TentativeReject,TentativeAccept,Travel,Undo,Update,UpdateComment,UpdateMeta,View,Workspace,Digest,Folder,Cell,Share
 */
@Serializable
enum class ActivityObjectType(val value: kotlin.String) {

    @SerialName(value = "BaseObject")
    BaseObject("BaseObject"),

    @SerialName(value = "Activity")
    Activity("Activity"),

    @SerialName(value = "Link")
    Link("Link"),

    @SerialName(value = "Mention")
    Mention("Mention"),

    @SerialName(value = "Collection")
    Collection("Collection"),

    @SerialName(value = "OrderedCollection")
    OrderedCollection("OrderedCollection"),

    @SerialName(value = "CollectionPage")
    CollectionPage("CollectionPage"),

    @SerialName(value = "OrderedCollectionPage")
    OrderedCollectionPage("OrderedCollectionPage"),

    @SerialName(value = "Application")
    Application("Application"),

    @SerialName(value = "Group")
    Group("Group"),

    @SerialName(value = "Organization")
    Organization("Organization"),

    @SerialName(value = "Person")
    Person("Person"),

    @SerialName(value = "Service")
    Service("Service"),

    @SerialName(value = "Article")
    Article("Article"),

    @SerialName(value = "Audio")
    Audio("Audio"),

    @SerialName(value = "Document")
    Document("Document"),

    @SerialName(value = "Event")
    Event("Event"),

    @SerialName(value = "Image")
    Image("Image"),

    @SerialName(value = "Note")
    Note("Note"),

    @SerialName(value = "Page")
    Page("Page"),

    @SerialName(value = "Place")
    Place("Place"),

    @SerialName(value = "Profile")
    Profile("Profile"),

    @SerialName(value = "Relationship")
    Relationship("Relationship"),

    @SerialName(value = "Tombstone")
    Tombstone("Tombstone"),

    @SerialName(value = "Video")
    Video("Video"),

    @SerialName(value = "Accept")
    Accept("Accept"),

    @SerialName(value = "Add")
    Add("Add"),

    @SerialName(value = "Announce")
    Announce("Announce"),

    @SerialName(value = "Arrive")
    Arrive("Arrive"),

    @SerialName(value = "Block")
    Block("Block"),

    @SerialName(value = "Create")
    Create("Create"),

    @SerialName(value = "Delete")
    Delete("Delete"),

    @SerialName(value = "Dislike")
    Dislike("Dislike"),

    @SerialName(value = "Flag")
    Flag("Flag"),

    @SerialName(value = "Follow")
    Follow("Follow"),

    @SerialName(value = "Ignore")
    Ignore("Ignore"),

    @SerialName(value = "Invite")
    Invite("Invite"),

    @SerialName(value = "Join")
    Join("Join"),

    @SerialName(value = "Leave")
    Leave("Leave"),

    @SerialName(value = "Like")
    Like("Like"),

    @SerialName(value = "Listen")
    Listen("Listen"),

    @SerialName(value = "Move")
    Move("Move"),

    @SerialName(value = "Offer")
    Offer("Offer"),

    @SerialName(value = "Question")
    Question("Question"),

    @SerialName(value = "Reject")
    Reject("Reject"),

    @SerialName(value = "Read")
    Read("Read"),

    @SerialName(value = "Remove")
    Remove("Remove"),

    @SerialName(value = "TentativeReject")
    TentativeReject("TentativeReject"),

    @SerialName(value = "TentativeAccept")
    TentativeAccept("TentativeAccept"),

    @SerialName(value = "Travel")
    Travel("Travel"),

    @SerialName(value = "Undo")
    Undo("Undo"),

    @SerialName(value = "Update")
    Update("Update"),

    @SerialName(value = "UpdateComment")
    UpdateComment("UpdateComment"),

    @SerialName(value = "UpdateMeta")
    UpdateMeta("UpdateMeta"),

    @SerialName(value = "View")
    View("View"),

    @SerialName(value = "Workspace")
    Workspace("Workspace"),

    @SerialName(value = "Digest")
    Digest("Digest"),

    @SerialName(value = "Folder")
    Folder("Folder"),

    @SerialName(value = "Cell")
    Cell("Cell"),

    @SerialName(value = "Share")
    Share("Share");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is ActivityObjectType) "$data" else null

        /**
         * Returns a valid [ActivityObjectType] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): ActivityObjectType? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

