/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.wire.kalium.cells.sdk.kmp.model

import com.wire.kalium.cells.sdk.kmp.model.ActivityObjectType

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param atContext 
 * @param accuracy 
 * @param actor 
 * @param altitude 
 * @param anyOf 
 * @param attachment 
 * @param attributedTo 
 * @param audience 
 * @param bcc 
 * @param bto 
 * @param cc 
 * @param closed 
 * @param content 
 * @param current 
 * @param deleted 
 * @param duration 
 * @param endTime 
 * @param first 
 * @param formerType 
 * @param generator 
 * @param height 
 * @param href 
 * @param hreflang 
 * @param icon 
 * @param id 
 * @param image 
 * @param inReplyTo 
 * @param instrument 
 * @param items 
 * @param last 
 * @param latitude 
 * @param location 
 * @param longitude 
 * @param markdown 
 * @param mediaType 
 * @param name 
 * @param next 
 * @param `object` 
 * @param oneOf 
 * @param origin 
 * @param partOf 
 * @param prev 
 * @param preview 
 * @param published 
 * @param radius 
 * @param rel 
 * @param relationship 
 * @param replies 
 * @param result 
 * @param startTime 
 * @param subject 
 * @param summary 
 * @param tag 
 * @param target 
 * @param to 
 * @param totalItems 
 * @param type 
 * @param units 
 * @param updated 
 * @param url 
 * @param width 
 */
@Serializable

data class ActivityObject (

    @SerialName(value = "@context") val atContext: kotlin.String? = null,

    @SerialName(value = "accuracy") val accuracy: kotlin.Float? = null,

    @SerialName(value = "actor") val actor: ActivityObject? = null,

    @SerialName(value = "altitude") val altitude: kotlin.Float? = null,

    @SerialName(value = "anyOf") val anyOf: ActivityObject? = null,

    @SerialName(value = "attachment") val attachment: ActivityObject? = null,

    @SerialName(value = "attributedTo") val attributedTo: ActivityObject? = null,

    @SerialName(value = "audience") val audience: ActivityObject? = null,

    @SerialName(value = "bcc") val bcc: ActivityObject? = null,

    @SerialName(value = "bto") val bto: ActivityObject? = null,

    @SerialName(value = "cc") val cc: ActivityObject? = null,

    @SerialName(value = "closed") val closed: kotlin.time.Instant? = null,

    @SerialName(value = "content") val content: ActivityObject? = null,

    @SerialName(value = "current") val current: ActivityObject? = null,

    @SerialName(value = "deleted") val deleted: kotlin.time.Instant? = null,

    @SerialName(value = "duration") val duration: kotlin.time.Instant? = null,

    @SerialName(value = "endTime") val endTime: kotlin.time.Instant? = null,

    @SerialName(value = "first") val first: ActivityObject? = null,

    @SerialName(value = "formerType") val formerType: ActivityObjectType? = ActivityObjectType.BaseObject,

    @SerialName(value = "generator") val generator: ActivityObject? = null,

    @SerialName(value = "height") val height: kotlin.Int? = null,

    @SerialName(value = "href") val href: kotlin.String? = null,

    @SerialName(value = "hreflang") val hreflang: kotlin.String? = null,

    @SerialName(value = "icon") val icon: ActivityObject? = null,

    @SerialName(value = "id") val id: kotlin.String? = null,

    @SerialName(value = "image") val image: ActivityObject? = null,

    @SerialName(value = "inReplyTo") val inReplyTo: ActivityObject? = null,

    @SerialName(value = "instrument") val instrument: ActivityObject? = null,

    @SerialName(value = "items") val items: kotlin.collections.List<ActivityObject>? = null,

    @SerialName(value = "last") val last: ActivityObject? = null,

    @SerialName(value = "latitude") val latitude: kotlin.Float? = null,

    @SerialName(value = "location") val location: ActivityObject? = null,

    @SerialName(value = "longitude") val longitude: kotlin.Float? = null,

    @SerialName(value = "markdown") val markdown: kotlin.String? = null,

    @SerialName(value = "mediaType") val mediaType: kotlin.String? = null,

    @SerialName(value = "name") val name: kotlin.String? = null,

    @SerialName(value = "next") val next: ActivityObject? = null,

    @SerialName(value = "object") val `object`: ActivityObject? = null,

    @SerialName(value = "oneOf") val oneOf: ActivityObject? = null,

    @SerialName(value = "origin") val origin: ActivityObject? = null,

    @SerialName(value = "partOf") val partOf: ActivityObject? = null,

    @SerialName(value = "prev") val prev: ActivityObject? = null,

    @SerialName(value = "preview") val preview: ActivityObject? = null,

    @SerialName(value = "published") val published: kotlin.time.Instant? = null,

    @SerialName(value = "radius") val radius: kotlin.Float? = null,

    @SerialName(value = "rel") val rel: kotlin.String? = null,

    @SerialName(value = "relationship") val relationship: ActivityObject? = null,

    @SerialName(value = "replies") val replies: ActivityObject? = null,

    @SerialName(value = "result") val result: ActivityObject? = null,

    @SerialName(value = "startTime") val startTime: kotlin.time.Instant? = null,

    @SerialName(value = "subject") val subject: ActivityObject? = null,

    @SerialName(value = "summary") val summary: kotlin.String? = null,

    @SerialName(value = "tag") val tag: ActivityObject? = null,

    @SerialName(value = "target") val target: ActivityObject? = null,

    @SerialName(value = "to") val to: ActivityObject? = null,

    @SerialName(value = "totalItems") val totalItems: kotlin.Int? = null,

    @SerialName(value = "type") val type: ActivityObjectType? = ActivityObjectType.BaseObject,

    @SerialName(value = "units") val units: kotlin.String? = null,

    @SerialName(value = "updated") val updated: kotlin.time.Instant? = null,

    @SerialName(value = "url") val url: ActivityObject? = null,

    @SerialName(value = "width") val width: kotlin.Int? = null

) {


}

