/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.wire.kalium.cells.sdk.kmp.model

import com.wire.kalium.cells.sdk.kmp.model.ServiceResourcePolicyQuery

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param metaUuids 
 * @param namespace 
 * @param nodeUuids 
 * @param resourceQuery 
 * @param resourceSubjectOwner 
 */
@Serializable

data class IdmSearchUserMetaRequest (

    @SerialName(value = "MetaUuids") val metaUuids: kotlin.collections.List<kotlin.String>? = null,

    @SerialName(value = "Namespace") val namespace: kotlin.String? = null,

    @SerialName(value = "NodeUuids") val nodeUuids: kotlin.collections.List<kotlin.String>? = null,

    @SerialName(value = "ResourceQuery") val resourceQuery: ServiceResourcePolicyQuery? = null,

    @SerialName(value = "ResourceSubjectOwner") val resourceSubjectOwner: kotlin.String? = null

) {


}

