/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.wire.kalium.cells.sdk.kmp.model

import com.wire.kalium.cells.sdk.kmp.model.ServiceResourcePolicy

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param indexable 
 * @param jsonDefinition 
 * @param label 
 * @param namespace 
 * @param order 
 * @param policies 
 * @param policiesContextEditable 
 */
@Serializable

data class IdmUserMetaNamespace (

    @SerialName(value = "Indexable") val indexable: kotlin.Boolean? = null,

    @SerialName(value = "JsonDefinition") val jsonDefinition: kotlin.String? = null,

    @SerialName(value = "Label") val label: kotlin.String? = null,

    @SerialName(value = "Namespace") val namespace: kotlin.String? = null,

    @SerialName(value = "Order") val order: kotlin.Int? = null,

    @SerialName(value = "Policies") val policies: kotlin.collections.List<ServiceResourcePolicy>? = null,

    @SerialName(value = "PoliciesContextEditable") val policiesContextEditable: kotlin.Boolean? = null

) {


}

