/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.wire.kalium.cells.sdk.kmp.model


import kotlinx.serialization.*

/**
 * 
 *
 * Values: None,Pause,Resume,Stop,Delete,RunOnce,Inactive,Active
 */
@Serializable
enum class JobsCommand(val value: kotlin.String) {

    @SerialName(value = "None")
    None("None"),

    @SerialName(value = "Pause")
    Pause("Pause"),

    @SerialName(value = "Resume")
    Resume("Resume"),

    @SerialName(value = "Stop")
    Stop("Stop"),

    @SerialName(value = "Delete")
    Delete("Delete"),

    @SerialName(value = "RunOnce")
    RunOnce("RunOnce"),

    @SerialName(value = "Inactive")
    Inactive("Inactive"),

    @SerialName(value = "Active")
    Active("Active");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is JobsCommand) "$data" else null

        /**
         * Returns a valid [JobsCommand] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): JobsCommand? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

