/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.wire.kalium.cells.sdk.kmp.model


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param exclude 
 * @param prefix 
 */
@Serializable

data class LookupFilterPathPrefix (

    @SerialName(value = "Exclude") val exclude: kotlin.Boolean? = null,

    @SerialName(value = "Prefix") val prefix: kotlin.String? = null

) {


}

