/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.wire.kalium.cells.sdk.kmp.model


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param max 
 * @param min 
 * @param relativeDuration 
 */
@Serializable

data class LookupFilterDateRange (

    @SerialName(value = "Max") val max: kotlin.String? = null,

    @SerialName(value = "Min") val min: kotlin.String? = null,

    @SerialName(value = "RelativeDuration") val relativeDuration: kotlin.String? = null

) {


}

