/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.wire.kalium.cells.sdk.kmp.model

import com.wire.kalium.cells.sdk.kmp.model.LookupFilterTextSearchIn

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param searchIn 
 * @param term 
 */
@Serializable

data class LookupFilterTextSearch (

    @SerialName(value = "SearchIn") val searchIn: LookupFilterTextSearchIn? = LookupFilterTextSearchIn.BaseName,

    @SerialName(value = "Term") val term: kotlin.String? = null

) {


}

