/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.wire.kalium.cells.sdk.kmp.model


import kotlinx.serialization.*

/**
 * 
 *
 * Values: Must,Should,Not
 */
@Serializable
enum class LookupFilterMetaFilterOp(val value: kotlin.String) {

    @SerialName(value = "Must")
    Must("Must"),

    @SerialName(value = "Should")
    Should("Should"),

    @SerialName(value = "Not")
    Not("Not");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is LookupFilterMetaFilterOp) "$data" else null

        /**
         * Returns a valid [LookupFilterMetaFilterOp] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): LookupFilterMetaFilterOp? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

