/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.wire.kalium.cells.sdk.kmp.model

import com.wire.kalium.cells.sdk.kmp.model.StatusFilterDeletedStatus
import com.wire.kalium.cells.sdk.kmp.model.StatusFilterDraftStatus

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param deleted 
 * @param draft 
 * @param hasPublicLink 
 * @param isBookmarked 
 * @param isDraft 
 */
@Serializable

data class LookupFilterStatusFilter (

    @SerialName(value = "Deleted") val deleted: StatusFilterDeletedStatus? = StatusFilterDeletedStatus.Not,

    @SerialName(value = "Draft") val draft: StatusFilterDraftStatus? = StatusFilterDraftStatus.DraftNot,

    @SerialName(value = "HasPublicLink") val hasPublicLink: kotlin.Boolean? = null,

    @SerialName(value = "IsBookmarked") val isBookmarked: kotlin.Boolean? = null,

    @SerialName(value = "IsDraft") val isDraft: kotlin.Boolean? = null

) {


}

