/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.wire.kalium.cells.sdk.kmp.model

import com.wire.kalium.cells.sdk.kmp.model.LookupFilterMetaFilterOp

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param namespace 
 * @param operation 
 * @param term 
 */
@Serializable

data class LookupFilterMetaFilter (

    @SerialName(value = "Namespace") val namespace: kotlin.String? = null,

    @SerialName(value = "Operation") val operation: LookupFilterMetaFilterOp? = LookupFilterMetaFilterOp.Must,

    @SerialName(value = "Term") val term: kotlin.String? = null

) {


}

