/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.wire.kalium.cells.sdk.kmp.model

import com.wire.kalium.cells.sdk.kmp.model.RestNode
import com.wire.kalium.cells.sdk.kmp.model.RestPublishCascadeResult

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param cascadeResults 
 * @param node 
 */
@Serializable

data class RestPublishNodeResponse (

    @SerialName(value = "CascadeResults") val cascadeResults: kotlin.collections.List<RestPublishCascadeResult>? = null,

    @SerialName(value = "Node") val node: RestNode? = null

) {


}

