/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.wire.kalium.cells.sdk.kmp.model

import com.wire.kalium.cells.sdk.kmp.model.IdmWorkspaceScope

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Current workspace information, maybe published on the root node of a workspace
 *
 * @param slug 
 * @param uuid 
 * @param description 
 * @param isRoot 
 * @param isVirtualRoot 
 * @param label 
 * @param permissions 
 * @param quota 
 * @param quotaUsage 
 * @param scope 
 * @param skipRecycle 
 * @param syncable 
 */
@Serializable

data class RestContextWorkspace (

    @SerialName(value = "Slug") @Required val slug: kotlin.String,

    @SerialName(value = "Uuid") @Required val uuid: kotlin.String,

    @SerialName(value = "Description") val description: kotlin.String? = null,

    @SerialName(value = "IsRoot") val isRoot: kotlin.Boolean? = null,

    @SerialName(value = "IsVirtualRoot") val isVirtualRoot: kotlin.Boolean? = null,

    @SerialName(value = "Label") val label: kotlin.String? = null,

    @SerialName(value = "Permissions") val permissions: kotlin.String? = null,

    @SerialName(value = "Quota") val quota: kotlin.String? = null,

    @SerialName(value = "QuotaUsage") val quotaUsage: kotlin.String? = null,

    @SerialName(value = "Scope") val scope: IdmWorkspaceScope? = IdmWorkspaceScope.ANY,

    @SerialName(value = "SkipRecycle") val skipRecycle: kotlin.Boolean? = null,

    @SerialName(value = "Syncable") val syncable: kotlin.Boolean? = null

) {


}

