/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.wire.kalium.cells.sdk.kmp.model

import com.wire.kalium.cells.sdk.kmp.model.TreeNode

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param children 
 * @param node 
 */
@Serializable

data class RestTemplateNode (

    @SerialName(value = "Children") val children: kotlin.collections.Map<kotlin.String, TreeNode>? = null,

    @SerialName(value = "Node") val node: TreeNode? = null

) {


}

