/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.wire.kalium.cells.sdk.kmp.model

import com.wire.kalium.cells.sdk.kmp.model.RestNode
import com.wire.kalium.cells.sdk.kmp.model.RestPagination
import com.wire.kalium.cells.sdk.kmp.model.TreeSearchFacet

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param facets 
 * @param nodes 
 * @param pagination 
 */
@Serializable

data class RestNodeCollection (

    @SerialName(value = "Facets") val facets: kotlin.collections.List<TreeSearchFacet>? = null,

    @SerialName(value = "Nodes") val nodes: kotlin.collections.List<RestNode>? = null,

    @SerialName(value = "Pagination") val pagination: RestPagination? = null

) {


}

