/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.wire.kalium.cells.sdk.kmp.model


import kotlinx.serialization.*

/**
 * 
 *
 * Values: Performed,Background
 */
@Serializable
enum class RestActionStatus(val value: kotlin.String) {

    @SerialName(value = "Performed")
    Performed("Performed"),

    @SerialName(value = "Background")
    Background("Background");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is RestActionStatus) "$data" else null

        /**
         * Returns a valid [RestActionStatus] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): RestActionStatus? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

