/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.wire.kalium.cells.sdk.kmp.model

import com.wire.kalium.cells.sdk.kmp.model.RestMetaToggle
import com.wire.kalium.cells.sdk.kmp.model.RestMetaUpdate

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param bookmark 
 * @param contentLock 
 * @param metaUpdates 
 */
@Serializable

data class RestNodeUpdates (

    @SerialName(value = "Bookmark") val bookmark: RestMetaToggle? = null,

    @SerialName(value = "ContentLock") val contentLock: RestMetaToggle? = null,

    @SerialName(value = "MetaUpdates") val metaUpdates: kotlin.collections.List<RestMetaUpdate>? = null

) {


}

