/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.wire.kalium.cells.sdk.kmp.model

import com.wire.kalium.cells.sdk.kmp.model.RestTemplateNode
import com.wire.kalium.cells.sdk.kmp.model.ServiceResourcePolicy

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param editable 
 * @param label 
 * @param node 
 * @param policies 
 * @param UUID 
 */
@Serializable

data class RestTemplate (

    @SerialName(value = "Editable") val editable: kotlin.Boolean? = null,

    @SerialName(value = "Label") val label: kotlin.String? = null,

    @SerialName(value = "Node") val node: RestTemplateNode? = null,

    @SerialName(value = "Policies") val policies: kotlin.collections.List<ServiceResourcePolicy>? = null,

    @SerialName(value = "UUID") val UUID: kotlin.String? = null

) {


}

