/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.wire.kalium.cells.sdk.kmp.model

import com.wire.kalium.cells.sdk.kmp.model.RestShareLinkAccessType
import com.wire.kalium.cells.sdk.kmp.model.RestShareLinkTargetUser
import com.wire.kalium.cells.sdk.kmp.model.ServiceResourcePolicy
import com.wire.kalium.cells.sdk.kmp.model.TreeNode

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param accessEnd 
 * @param accessStart 
 * @param currentDownloads 
 * @param description 
 * @param label 
 * @param linkHash 
 * @param linkUrl 
 * @param maxDownloads 
 * @param passwordRequired 
 * @param permissions 
 * @param policies 
 * @param policiesContextEditable 
 * @param restrictToTargetUsers 
 * @param rootNodes 
 * @param targetUsers 
 * @param userLogin 
 * @param userUuid 
 * @param uuid 
 * @param viewTemplateName 
 */
@Serializable

data class RestShareLink (

    @SerialName(value = "AccessEnd") val accessEnd: kotlin.String? = null,

    @SerialName(value = "AccessStart") val accessStart: kotlin.String? = null,

    @SerialName(value = "CurrentDownloads") val currentDownloads: kotlin.String? = null,

    @SerialName(value = "Description") val description: kotlin.String? = null,

    @SerialName(value = "Label") val label: kotlin.String? = null,

    @SerialName(value = "LinkHash") val linkHash: kotlin.String? = null,

    @SerialName(value = "LinkUrl") val linkUrl: kotlin.String? = null,

    @SerialName(value = "MaxDownloads") val maxDownloads: kotlin.String? = null,

    @SerialName(value = "PasswordRequired") val passwordRequired: kotlin.Boolean? = null,

    @SerialName(value = "Permissions") val permissions: kotlin.collections.List<RestShareLinkAccessType>? = null,

    @SerialName(value = "Policies") val policies: kotlin.collections.List<ServiceResourcePolicy>? = null,

    @SerialName(value = "PoliciesContextEditable") val policiesContextEditable: kotlin.Boolean? = null,

    @SerialName(value = "RestrictToTargetUsers") val restrictToTargetUsers: kotlin.Boolean? = null,

    @SerialName(value = "RootNodes") val rootNodes: kotlin.collections.List<TreeNode>? = null,

    @SerialName(value = "TargetUsers") val targetUsers: kotlin.collections.Map<kotlin.String, RestShareLinkTargetUser>? = null,

    @SerialName(value = "UserLogin") val userLogin: kotlin.String? = null,

    @SerialName(value = "UserUuid") val userUuid: kotlin.String? = null,

    @SerialName(value = "Uuid") val uuid: kotlin.String? = null,

    @SerialName(value = "ViewTemplateName") val viewTemplateName: kotlin.String? = null

) {


}

