/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.wire.kalium.cells.sdk.kmp.model


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param code 
 * @param detail 
 * @param meta 
 * @param source 
 * @param title 
 */
@Serializable

data class RestError (

    @SerialName(value = "Code") val code: kotlin.String? = null,

    @SerialName(value = "Detail") val detail: kotlin.String? = null,

    @SerialName(value = "Meta") val meta: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,

    @SerialName(value = "Source") val source: kotlin.String? = null,

    @SerialName(value = "Title") val title: kotlin.String? = null

) {


}

