/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.wire.kalium.cells.sdk.kmp.model

import com.wire.kalium.cells.sdk.kmp.model.RestIncomingNode

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param inputs 
 * @param recursive 
 */
@Serializable

data class RestCreateRequest (

    @SerialName(value = "Inputs") @Required val inputs: kotlin.collections.List<RestIncomingNode>,

    @SerialName(value = "Recursive") val recursive: kotlin.Boolean? = null

) {


}

