/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.wire.kalium.cells.sdk.kmp.model


import kotlinx.serialization.*

/**
 * 
 *
 * Values: Default,NodeReadOnly,NodeWriteOnly,LevelReadOnly
 */
@Serializable
enum class RestMode(val value: kotlin.String) {

    @SerialName(value = "Default")
    Default("Default"),

    @SerialName(value = "NodeReadOnly")
    NodeReadOnly("NodeReadOnly"),

    @SerialName(value = "NodeWriteOnly")
    NodeWriteOnly("NodeWriteOnly"),

    @SerialName(value = "LevelReadOnly")
    LevelReadOnly("LevelReadOnly");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is RestMode) "$data" else null

        /**
         * Returns a valid [RestMode] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): RestMode? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

