/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.wire.kalium.cells.sdk.kmp.model


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param archiveFormat 
 * @param targetPath 
 */
@Serializable

data class RestActionOptionsExtractCompress (

    @SerialName(value = "ArchiveFormat") @Required val archiveFormat: kotlin.String,

    @SerialName(value = "TargetPath") @Required val targetPath: kotlin.String

) {


}

