/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.wire.kalium.cells.sdk.kmp.model

import com.wire.kalium.cells.sdk.kmp.model.RestFlag
import com.wire.kalium.cells.sdk.kmp.model.RestLookupFilter
import com.wire.kalium.cells.sdk.kmp.model.RestLookupScope
import com.wire.kalium.cells.sdk.kmp.model.RestNodeLocators
import com.wire.kalium.cells.sdk.kmp.model.TreeQuery

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param filters 
 * @param flags 
 * @param limit 
 * @param locators 
 * @param offset 
 * @param query 
 * @param scope 
 * @param sortDirDesc 
 * @param sortField 
 */
@Serializable

data class RestLookupRequest (

    @SerialName(value = "Filters") val filters: RestLookupFilter? = null,

    @SerialName(value = "Flags") val flags: kotlin.collections.List<RestFlag>? = null,

    @SerialName(value = "Limit") val limit: kotlin.String? = null,

    @SerialName(value = "Locators") val locators: RestNodeLocators? = null,

    @SerialName(value = "Offset") val offset: kotlin.String? = null,

    @SerialName(value = "Query") val query: TreeQuery? = null,

    @SerialName(value = "Scope") val scope: RestLookupScope? = null,

    @SerialName(value = "SortDirDesc") val sortDirDesc: kotlin.Boolean? = null,

    @SerialName(value = "SortField") val sortField: kotlin.String? = null

) {


}

