/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.wire.kalium.cells.sdk.kmp.model

import com.wire.kalium.cells.sdk.kmp.model.RestNodeLocator

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param nodes 
 * @param root 
 * @param rootRelativeDepth 
 */
@Serializable

data class RestLookupScope (

    @SerialName(value = "Nodes") val nodes: kotlin.collections.List<RestNodeLocator>? = null,

    @SerialName(value = "Root") val root: RestNodeLocator? = null,

    @SerialName(value = "RootRelativeDepth") val rootRelativeDepth: kotlin.Int? = null

) {


}

