/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.wire.kalium.cells.sdk.kmp.model


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param height 
 * @param jsonEXIF 
 * @param orientation 
 * @param width 
 */
@Serializable

data class RestImageMeta (

    @SerialName(value = "Height") val height: kotlin.Int? = null,

    @SerialName(value = "JsonEXIF") val jsonEXIF: kotlin.String? = null,

    @SerialName(value = "Orientation") val orientation: kotlin.Int? = null,

    @SerialName(value = "Width") val width: kotlin.Int? = null

) {


}

