/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.wire.kalium.cells.sdk.kmp.model

import com.wire.kalium.cells.sdk.kmp.model.RestFlag
import com.wire.kalium.cells.sdk.kmp.model.RestVersionsTypes

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param filterBy 
 * @param flags 
 * @param limit 
 * @param offset 
 * @param sortDirDesc 
 * @param sortField 
 */
@Serializable

data class RestNodeVersionsFilter (

    @SerialName(value = "FilterBy") val filterBy: RestVersionsTypes? = RestVersionsTypes.VersionsAll,

    @SerialName(value = "Flags") val flags: kotlin.collections.List<RestFlag>? = null,

    @SerialName(value = "Limit") val limit: kotlin.String? = null,

    @SerialName(value = "Offset") val offset: kotlin.String? = null,

    @SerialName(value = "SortDirDesc") val sortDirDesc: kotlin.Boolean? = null,

    @SerialName(value = "SortField") val sortField: kotlin.String? = null

) {


}

