/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.wire.kalium.cells.sdk.kmp.model

import com.wire.kalium.cells.sdk.kmp.model.RestActionStatus
import com.wire.kalium.cells.sdk.kmp.model.RestBackgroundAction
import com.wire.kalium.cells.sdk.kmp.model.RestNode

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param affectedNodes 
 * @param backgroundActions 
 * @param status 
 */
@Serializable

data class RestPerformActionResponse (

    @SerialName(value = "AffectedNodes") val affectedNodes: kotlin.collections.List<RestNode>? = null,

    @SerialName(value = "BackgroundActions") val backgroundActions: kotlin.collections.List<RestBackgroundAction>? = null,

    @SerialName(value = "Status") val status: RestActionStatus? = RestActionStatus.Performed

) {


}

