/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.wire.kalium.cells.sdk.kmp.model

import com.wire.kalium.cells.sdk.kmp.model.RestNode
import com.wire.kalium.cells.sdk.kmp.model.RestNodeLocator

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param exists 
 * @param inputLocator 
 * @param nextPath 
 * @param node 
 */
@Serializable

data class RestCheckResult (

    @SerialName(value = "Exists") val exists: kotlin.Boolean? = null,

    @SerialName(value = "InputLocator") val inputLocator: RestNodeLocator? = null,

    @SerialName(value = "NextPath") val nextPath: kotlin.String? = null,

    @SerialName(value = "Node") val node: RestNode? = null

) {


}

