/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.wire.kalium.cells.sdk.kmp.model

import com.wire.kalium.cells.sdk.kmp.model.RestNsOp

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param operation 
 * @param propertyValues 
 */
@Serializable

data class RestNamespaceValuesOperation (

    @SerialName(value = "Operation") @Required val operation: RestNsOp = RestNsOp.PUT,

    @SerialName(value = "Values") @Required val propertyValues: kotlin.collections.List<kotlin.String>

) {


}

