/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.wire.kalium.cells.sdk.kmp.model

import com.wire.kalium.cells.sdk.kmp.model.RestNodeLocator
import com.wire.kalium.cells.sdk.kmp.model.RestUserMeta
import com.wire.kalium.cells.sdk.kmp.model.TreeNodeType

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param locator 
 * @param type 
 * @param contentType 
 * @param draftMode 
 * @param knownSize 
 * @param metadata 
 * @param resourceUuid 
 * @param templateUuid 
 * @param versionId 
 */
@Serializable

data class RestIncomingNode (

    @SerialName(value = "Locator") @Required val locator: RestNodeLocator,

    @SerialName(value = "Type") @Required val type: TreeNodeType = TreeNodeType.UNKNOWN,

    @SerialName(value = "ContentType") val contentType: kotlin.String? = null,

    @SerialName(value = "DraftMode") val draftMode: kotlin.Boolean? = null,

    @SerialName(value = "KnownSize") val knownSize: kotlin.String? = null,

    @SerialName(value = "Metadata") val metadata: kotlin.collections.List<RestUserMeta>? = null,

    @SerialName(value = "ResourceUuid") val resourceUuid: kotlin.String? = null,

    @SerialName(value = "TemplateUuid") val templateUuid: kotlin.String? = null,

    @SerialName(value = "VersionId") val versionId: kotlin.String? = null

) {


}

