/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.wire.kalium.cells.sdk.kmp.model


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param versionId 
 * @param description 
 * @param draft 
 * @param etag 
 * @param isHead 
 * @param mtime 
 * @param ownerName 
 * @param ownerUuid 
 * @param propertySize 
 */
@Serializable

data class RestVersion (

    @SerialName(value = "VersionId") @Required val versionId: kotlin.String,

    @SerialName(value = "Description") val description: kotlin.String? = null,

    @SerialName(value = "Draft") val draft: kotlin.Boolean? = null,

    @SerialName(value = "ETag") val etag: kotlin.String? = null,

    @SerialName(value = "IsHead") val isHead: kotlin.Boolean? = null,

    @SerialName(value = "MTime") val mtime: kotlin.String? = null,

    @SerialName(value = "OwnerName") val ownerName: kotlin.String? = null,

    @SerialName(value = "OwnerUuid") val ownerUuid: kotlin.String? = null,

    @SerialName(value = "Size") val propertySize: kotlin.String? = null

) {


}

