/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.wire.kalium.cells.sdk.kmp.model

import com.wire.kalium.cells.sdk.kmp.model.LookupFilterDateRange
import com.wire.kalium.cells.sdk.kmp.model.LookupFilterMetaFilter
import com.wire.kalium.cells.sdk.kmp.model.LookupFilterPathPrefix
import com.wire.kalium.cells.sdk.kmp.model.LookupFilterSizeRange
import com.wire.kalium.cells.sdk.kmp.model.LookupFilterStatusFilter
import com.wire.kalium.cells.sdk.kmp.model.LookupFilterTextSearch
import com.wire.kalium.cells.sdk.kmp.model.TreeNodeType

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param date 
 * @param extensions 
 * @param freeExpression 
 * @param metadata 
 * @param prefixes 
 * @param propertySize 
 * @param status 
 * @param text 
 * @param type 
 */
@Serializable

data class RestLookupFilter (

    @SerialName(value = "Date") val date: LookupFilterDateRange? = null,

    @SerialName(value = "Extensions") val extensions: kotlin.collections.List<kotlin.String>? = null,

    @SerialName(value = "FreeExpression") val freeExpression: kotlin.String? = null,

    @SerialName(value = "Metadata") val metadata: kotlin.collections.List<LookupFilterMetaFilter>? = null,

    @SerialName(value = "Prefixes") val prefixes: kotlin.collections.List<LookupFilterPathPrefix>? = null,

    @SerialName(value = "Size") val propertySize: LookupFilterSizeRange? = null,

    @SerialName(value = "Status") val status: LookupFilterStatusFilter? = null,

    @SerialName(value = "Text") val text: LookupFilterTextSearch? = null,

    @SerialName(value = "Type") val type: TreeNodeType? = TreeNodeType.UNKNOWN

) {


}

