/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.wire.kalium.cells.sdk.kmp.model


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param encrypted 
 * @param versioned 
 */
@Serializable

data class RestDataSourceFeatures (

    @SerialName(value = "Encrypted") val encrypted: kotlin.Boolean? = null,

    @SerialName(value = "Versioned") val versioned: kotlin.Boolean? = null

) {


}

