/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.wire.kalium.cells.sdk.kmp.model


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param currentOffset 
 * @param currentPage 
 * @param limit 
 * @param nextOffset 
 * @param prevOffset 
 * @param total 
 * @param totalPages 
 */
@Serializable

data class RestPagination (

    @SerialName(value = "CurrentOffset") val currentOffset: kotlin.Int? = null,

    @SerialName(value = "CurrentPage") val currentPage: kotlin.Int? = null,

    @SerialName(value = "Limit") val limit: kotlin.Int? = null,

    @SerialName(value = "NextOffset") val nextOffset: kotlin.Int? = null,

    @SerialName(value = "PrevOffset") val prevOffset: kotlin.Int? = null,

    @SerialName(value = "Total") val total: kotlin.Int? = null,

    @SerialName(value = "TotalPages") val totalPages: kotlin.Int? = null

) {


}

