/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.wire.kalium.cells.sdk.kmp.model

import com.wire.kalium.cells.sdk.kmp.model.RestPreSignedURL

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param bucket 
 * @param contentType 
 * @param dimension 
 * @param error 
 * @param key 
 * @param preSignedGET 
 * @param processing 
 */
@Serializable

data class RestFilePreview (

    @SerialName(value = "Bucket") val bucket: kotlin.String? = null,

    @SerialName(value = "ContentType") val contentType: kotlin.String? = null,

    @SerialName(value = "Dimension") val dimension: kotlin.Int? = null,

    @SerialName(value = "Error") val error: kotlin.Boolean? = null,

    @SerialName(value = "Key") val key: kotlin.String? = null,

    @SerialName(value = "PreSignedGET") val preSignedGET: RestPreSignedURL? = null,

    @SerialName(value = "Processing") val processing: kotlin.Boolean? = null

) {


}

