/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.wire.kalium.cells.sdk.kmp.model

import com.wire.kalium.cells.sdk.kmp.model.MetaUpdateOp
import com.wire.kalium.cells.sdk.kmp.model.RestUserMeta

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param operation 
 * @param userMeta 
 */
@Serializable

data class RestMetaUpdate (

    @SerialName(value = "Operation") @Required val operation: MetaUpdateOp = MetaUpdateOp.PUT,

    @SerialName(value = "UserMeta") @Required val userMeta: RestUserMeta

) {


}

