/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.wire.kalium.cells.sdk.kmp.model


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param path 
 * @param uuid 
 */
@Serializable

data class RestNodeLocator (

    @SerialName(value = "Path") val path: kotlin.String? = null,

    @SerialName(value = "Uuid") val uuid: kotlin.String? = null

) {


}

