/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.wire.kalium.cells.sdk.kmp.model

import com.wire.kalium.cells.sdk.kmp.model.JobsTaskStatus

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param jobUuid 
 * @param name 
 * @param canPause 
 * @param canStop 
 * @param endTime 
 * @param hasProgress 
 * @param label 
 * @param progress 
 * @param startTime 
 * @param status 
 * @param statusMessage 
 */
@Serializable

data class RestBackgroundAction (

    @SerialName(value = "JobUuid") @Required val jobUuid: kotlin.String,

    @SerialName(value = "Name") @Required val name: kotlin.String,

    @SerialName(value = "CanPause") val canPause: kotlin.Boolean? = null,

    @SerialName(value = "CanStop") val canStop: kotlin.Boolean? = null,

    @SerialName(value = "EndTime") val endTime: kotlin.Int? = null,

    @SerialName(value = "HasProgress") val hasProgress: kotlin.Boolean? = null,

    @SerialName(value = "Label") val label: kotlin.String? = null,

    @SerialName(value = "Progress") val progress: kotlin.Float? = null,

    @SerialName(value = "StartTime") val startTime: kotlin.Int? = null,

    @SerialName(value = "Status") val status: JobsTaskStatus? = JobsTaskStatus.Unknown,

    @SerialName(value = "StatusMessage") val statusMessage: kotlin.String? = null

) {


}

