/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.wire.kalium.cells.sdk.kmp.model


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param versionId 
 * @param description 
 * @param isDraft 
 * @param isHead 
 * @param ownerUuid 
 */
@Serializable

data class RestVersionMeta (

    @SerialName(value = "VersionId") @Required val versionId: kotlin.String,

    @SerialName(value = "Description") val description: kotlin.String? = null,

    @SerialName(value = "IsDraft") val isDraft: kotlin.Boolean? = null,

    @SerialName(value = "IsHead") val isHead: kotlin.Boolean? = null,

    @SerialName(value = "OwnerUuid") val ownerUuid: kotlin.String? = null

) {


}

