/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.wire.kalium.cells.sdk.kmp.model

import com.wire.kalium.cells.sdk.kmp.model.ActivityObject
import com.wire.kalium.cells.sdk.kmp.model.ActivitySubscription
import com.wire.kalium.cells.sdk.kmp.model.RestContextWorkspace
import com.wire.kalium.cells.sdk.kmp.model.RestCountMeta
import com.wire.kalium.cells.sdk.kmp.model.RestDataSourceFeatures
import com.wire.kalium.cells.sdk.kmp.model.RestFilePreview
import com.wire.kalium.cells.sdk.kmp.model.RestImageMeta
import com.wire.kalium.cells.sdk.kmp.model.RestJsonMeta
import com.wire.kalium.cells.sdk.kmp.model.RestLockInfo
import com.wire.kalium.cells.sdk.kmp.model.RestMode
import com.wire.kalium.cells.sdk.kmp.model.RestShareLink
import com.wire.kalium.cells.sdk.kmp.model.RestUserMeta
import com.wire.kalium.cells.sdk.kmp.model.RestVersion
import com.wire.kalium.cells.sdk.kmp.model.RestVersionMeta
import com.wire.kalium.cells.sdk.kmp.model.TreeNodeType

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Representation of a file or folder
 *
 * @param path 
 * @param uuid 
 * @param activities 
 * @param contentHash 
 * @param contentLock 
 * @param contentType 
 * @param contextWorkspace 
 * @param dataSourceFeatures 
 * @param folderMeta 
 * @param hashingMethod 
 * @param imageMeta 
 * @param isBookmarked 
 * @param isDraft 
 * @param isRecycleBin 
 * @param isRecycled 
 * @param metadata 
 * @param mode 
 * @param modified Date instead of TS ?
 * @param previews 
 * @param shares 
 * @param propertySize 
 * @param storageETag 
 * @param subscriptions 
 * @param type 
 * @param userMetadata 
 * @param versionMeta 
 * @param versions 
 */
@Serializable

data class RestNode (

    @SerialName(value = "Path") @Required val path: kotlin.String,

    @SerialName(value = "Uuid") @Required val uuid: kotlin.String,

    @SerialName(value = "Activities") val activities: kotlin.collections.List<ActivityObject>? = null,

    @SerialName(value = "ContentHash") val contentHash: kotlin.String? = null,

    @SerialName(value = "ContentLock") val contentLock: RestLockInfo? = null,

    @SerialName(value = "ContentType") val contentType: kotlin.String? = null,

    @SerialName(value = "ContextWorkspace") val contextWorkspace: RestContextWorkspace? = null,

    @SerialName(value = "DataSourceFeatures") val dataSourceFeatures: RestDataSourceFeatures? = null,

    @SerialName(value = "FolderMeta") val folderMeta: kotlin.collections.List<RestCountMeta>? = null,

    @SerialName(value = "HashingMethod") val hashingMethod: kotlin.String? = null,

    @SerialName(value = "ImageMeta") val imageMeta: RestImageMeta? = null,

    @SerialName(value = "IsBookmarked") val isBookmarked: kotlin.Boolean? = null,

    @SerialName(value = "IsDraft") val isDraft: kotlin.Boolean? = null,

    @SerialName(value = "IsRecycleBin") val isRecycleBin: kotlin.Boolean? = null,

    @SerialName(value = "IsRecycled") val isRecycled: kotlin.Boolean? = null,

    @SerialName(value = "Metadata") val metadata: kotlin.collections.List<RestJsonMeta>? = null,

    @SerialName(value = "Mode") val mode: RestMode? = RestMode.Default,

    /* Date instead of TS ? */
    @SerialName(value = "Modified") val modified: kotlin.String? = null,

    @SerialName(value = "Previews") val previews: kotlin.collections.List<RestFilePreview>? = null,

    @SerialName(value = "Shares") val shares: kotlin.collections.List<RestShareLink>? = null,

    @SerialName(value = "Size") val propertySize: kotlin.String? = null,

    @SerialName(value = "StorageETag") val storageETag: kotlin.String? = null,

    @SerialName(value = "Subscriptions") val subscriptions: kotlin.collections.List<ActivitySubscription>? = null,

    @SerialName(value = "Type") val type: TreeNodeType? = TreeNodeType.UNKNOWN,

    @SerialName(value = "UserMetadata") val userMetadata: kotlin.collections.List<RestUserMeta>? = null,

    @SerialName(value = "VersionMeta") val versionMeta: RestVersionMeta? = null,

    @SerialName(value = "Versions") val versions: kotlin.collections.List<RestVersion>? = null

) {


}

