/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.wire.kalium.cells.sdk.kmp.model

import com.wire.kalium.cells.sdk.kmp.model.RestFilePreview
import com.wire.kalium.cells.sdk.kmp.model.RestPreSignedURL

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param versionId 
 * @param contentHash 
 * @param description 
 * @param draft 
 * @param etag 
 * @param editorURLs 
 * @param filePreviews 
 * @param isHead 
 * @param mtime 
 * @param ownerName 
 * @param ownerUuid 
 * @param preSignedGET 
 * @param propertySize 
 */
@Serializable

data class RestVersion (

    @SerialName(value = "VersionId") @Required val versionId: kotlin.String,

    @SerialName(value = "ContentHash") val contentHash: kotlin.String? = null,

    @SerialName(value = "Description") val description: kotlin.String? = null,

    @SerialName(value = "Draft") val draft: kotlin.Boolean? = null,

    @SerialName(value = "ETag") val etag: kotlin.String? = null,

    @SerialName(value = "EditorURLs") val editorURLs: kotlin.collections.Map<kotlin.String, RestPreSignedURL>? = null,

    @SerialName(value = "FilePreviews") val filePreviews: kotlin.collections.List<RestFilePreview>? = null,

    @SerialName(value = "IsHead") val isHead: kotlin.Boolean? = null,

    @SerialName(value = "MTime") val mtime: kotlin.String? = null,

    @SerialName(value = "OwnerName") val ownerName: kotlin.String? = null,

    @SerialName(value = "OwnerUuid") val ownerUuid: kotlin.String? = null,

    @SerialName(value = "PreSignedGET") val preSignedGET: RestPreSignedURL? = null,

    @SerialName(value = "Size") val propertySize: kotlin.String? = null

) {


}

