/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.wire.kalium.cells.sdk.kmp.model


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param display 
 * @param downloadCount 
 */
@Serializable

data class RestShareLinkTargetUser (

    @SerialName(value = "Display") val display: kotlin.String? = null,

    @SerialName(value = "DownloadCount") val downloadCount: kotlin.Int? = null

) {


}

