/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.wire.kalium.cells.sdk.kmp.model

import com.wire.kalium.cells.sdk.kmp.model.RestUserMeta

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param userMeta 
 */
@Serializable

data class RestUserMetaList (

    @SerialName(value = "UserMeta") val userMeta: kotlin.collections.List<RestUserMeta>? = null

) {


}

