/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.wire.kalium.cells.sdk.kmp.model


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param ignoreConflicts 
 * @param publish 
 */
@Serializable

data class RestPromoteParameters (

    @SerialName(value = "IgnoreConflicts") val ignoreConflicts: kotlin.Boolean? = null,

    @SerialName(value = "Publish") val publish: kotlin.Boolean? = null

) {


}

