/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.wire.kalium.cells.sdk.kmp.model

import com.wire.kalium.cells.sdk.kmp.model.RestNode

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param node 
 * @param published 
 * @param success 
 */
@Serializable

data class RestPromoteVersionResponse (

    @SerialName(value = "Node") val node: RestNode? = null,

    @SerialName(value = "Published") val published: kotlin.Boolean? = null,

    @SerialName(value = "Success") val success: kotlin.Boolean? = null

) {


}

