/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.wire.kalium.cells.sdk.kmp.model

import com.wire.kalium.cells.sdk.kmp.model.ServiceResourcePolicyAction

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param action 
 * @param any 
 * @param empty 
 * @param leftIdentifier 
 * @param subjects 
 */
@Serializable

data class ServiceResourcePolicyQuery (

    @SerialName(value = "Action") val action: ServiceResourcePolicyAction? = ServiceResourcePolicyAction.ANY,

    @SerialName(value = "Any") val any: kotlin.Boolean? = null,

    @SerialName(value = "Empty") val empty: kotlin.Boolean? = null,

    @SerialName(value = "LeftIdentifier") val leftIdentifier: kotlin.String? = null,

    @SerialName(value = "Subjects") val subjects: kotlin.collections.List<kotlin.String>? = null

) {


}

