/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.wire.kalium.cells.sdk.kmp.model

import com.wire.kalium.cells.sdk.kmp.model.ServiceResourcePolicyAction
import com.wire.kalium.cells.sdk.kmp.model.ServiceResourcePolicyPolicyEffect

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param action 
 * @param effect 
 * @param jsonConditions 
 * @param resource 
 * @param subject 
 * @param id 
 */
@Serializable

data class ServiceResourcePolicy (

    @SerialName(value = "Action") val action: ServiceResourcePolicyAction? = ServiceResourcePolicyAction.ANY,

    @SerialName(value = "Effect") val effect: ServiceResourcePolicyPolicyEffect? = ServiceResourcePolicyPolicyEffect.deny,

    @SerialName(value = "JsonConditions") val jsonConditions: kotlin.String? = null,

    @SerialName(value = "Resource") val resource: kotlin.String? = null,

    @SerialName(value = "Subject") val subject: kotlin.String? = null,

    @SerialName(value = "id") val id: kotlin.String? = null

) {


}

