/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.wire.kalium.cells.sdk.kmp.model

import com.wire.kalium.cells.sdk.kmp.model.TreeChangeLog
import com.wire.kalium.cells.sdk.kmp.model.TreeNodeType
import com.wire.kalium.cells.sdk.kmp.model.TreeWorkspaceRelativePath

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param appearsIn 
 * @param commits 
 * @param etag 
 * @param mtime 
 * @param metaStore 
 * @param mode Permission mode, like 0777. Stored as string using custom ModeString field.
 * @param modeString 
 * @param path 
 * @param propertySize 
 * @param type 
 * @param uuid 
 */
@Serializable

data class TreeNode (

    @SerialName(value = "AppearsIn") val appearsIn: kotlin.collections.List<TreeWorkspaceRelativePath>? = null,

    @SerialName(value = "Commits") val commits: kotlin.collections.List<TreeChangeLog>? = null,

    @SerialName(value = "Etag") val etag: kotlin.String? = null,

    @SerialName(value = "MTime") val mtime: kotlin.String? = null,

    @SerialName(value = "MetaStore") val metaStore: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,

    /* Permission mode, like 0777. Stored as string using custom ModeString field. */
    @SerialName(value = "Mode") val mode: kotlin.Int? = null,

    @SerialName(value = "ModeString") val modeString: kotlin.String? = null,

    @SerialName(value = "Path") val path: kotlin.String? = null,

    @SerialName(value = "Size") val propertySize: kotlin.String? = null,

    @SerialName(value = "Type") val type: TreeNodeType? = TreeNodeType.UNKNOWN,

    @SerialName(value = "Uuid") val uuid: kotlin.String? = null

) {


}

