/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.wire.kalium.cells.sdk.kmp.model


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param path 
 * @param wsLabel 
 * @param wsScope 
 * @param wsSlug 
 * @param wsUuid 
 */
@Serializable

data class TreeWorkspaceRelativePath (

    @SerialName(value = "Path") val path: kotlin.String? = null,

    @SerialName(value = "WsLabel") val wsLabel: kotlin.String? = null,

    @SerialName(value = "WsScope") val wsScope: kotlin.String? = null,

    @SerialName(value = "WsSlug") val wsSlug: kotlin.String? = null,

    @SerialName(value = "WsUuid") val wsUuid: kotlin.String? = null

) {


}

