/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.wire.kalium.cells.sdk.kmp.model


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param lat 
 * @param lon 
 */
@Serializable

data class TreeGeoPoint (

    @SerialName(value = "Lat") val lat: kotlin.Double? = null,

    @SerialName(value = "Lon") val lon: kotlin.Double? = null

) {


}

