/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.wire.kalium.cells.sdk.kmp.model

import com.wire.kalium.cells.sdk.kmp.model.TreeNode
import com.wire.kalium.cells.sdk.kmp.model.TreeNodeChangeEvent

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param `data` 
 * @param description 
 * @param event 
 * @param location 
 * @param mtime 
 * @param ownerUuid 
 * @param propertySize 
 * @param uuid 
 */
@Serializable

data class TreeChangeLog (

    @SerialName(value = "Data") val `data`: com.wire.kalium.cells.sdk.kmp.infrastructure.Base64ByteArray? = null,

    @SerialName(value = "Description") val description: kotlin.String? = null,

    @SerialName(value = "Event") val event: TreeNodeChangeEvent? = null,

    @SerialName(value = "Location") val location: TreeNode? = null,

    @SerialName(value = "MTime") val mtime: kotlin.String? = null,

    @SerialName(value = "OwnerUuid") val ownerUuid: kotlin.String? = null,

    @SerialName(value = "Size") val propertySize: kotlin.String? = null,

    @SerialName(value = "Uuid") val uuid: kotlin.String? = null

) {


}

