/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.wire.kalium.cells.sdk.kmp.model

import com.wire.kalium.cells.sdk.kmp.model.TreeNode
import com.wire.kalium.cells.sdk.kmp.model.TreeNodeChangeEventEventType

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param metadata 
 * @param optimistic 
 * @param silent 
 * @param source 
 * @param target 
 * @param type 
 */
@Serializable

data class TreeNodeChangeEvent (

    @SerialName(value = "Metadata") val metadata: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,

    @SerialName(value = "Optimistic") val optimistic: kotlin.Boolean? = null,

    @SerialName(value = "Silent") val silent: kotlin.Boolean? = null,

    @SerialName(value = "Source") val source: TreeNode? = null,

    @SerialName(value = "Target") val target: TreeNode? = null,

    @SerialName(value = "Type") val type: TreeNodeChangeEventEventType? = TreeNodeChangeEventEventType.CREATE

) {


}

