/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.wire.kalium.cells.sdk.kmp.model


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param count 
 * @param end 
 * @param fieldName 
 * @param label 
 * @param max 
 * @param min 
 * @param start 
 * @param term 
 */
@Serializable

data class TreeSearchFacet (

    @SerialName(value = "Count") val count: kotlin.Int? = null,

    @SerialName(value = "End") val end: kotlin.Int? = null,

    @SerialName(value = "FieldName") val fieldName: kotlin.String? = null,

    @SerialName(value = "Label") val label: kotlin.String? = null,

    @SerialName(value = "Max") val max: kotlin.String? = null,

    @SerialName(value = "Min") val min: kotlin.String? = null,

    @SerialName(value = "Start") val start: kotlin.Int? = null,

    @SerialName(value = "Term") val term: kotlin.String? = null

) {


}

