name: Publish To Maven Central

on:
  push:
    tags:
    ## TODO: make this more robust. Depend on a release? See https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows
      - 'v0.1.**'

jobs:
  publish:

    runs-on: ubuntu-latest
    if: github.repository == 'wireapp/cells-sdk-kmp'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

#      - name: Setup Android SDK
#        uses: android-actions/setup-android@v3
#      - name: Set version for tag
#        run: |
#          echo "ORG_GRADLE_PROJECT_VERSION_NAME=${{ github.ref_name }}" >> $GITHUB_ENV

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      # Simply add the expected local.properties file
      - name: Configure Gradle
        run: touch ./local.properties

      - name: Publish
        run: ./gradlew publishToMavenLocal
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_PWD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}

#      - name: Publish
#        run: ./gradlew publishAndReleaseToMavenCentral
#        env:
#          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_USERNAME }}
#          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_PWD }}
#          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_PRIVATE_KEY }}
#          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}
