name: Publish To Maven Central

on:
  push:
# Temp
#    branches:
#      - dev
    tags:      ## TODO: make this more robust. Depend on a release? See https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows
      - 'v0.1.**'

jobs:
  publish:

    #runs-on: ubuntu-latest
    runs-on: macos-latest
    # Define which environment we use to inject variables, see github repo >> settings >> environments
    environment: maven-central-publication
    if: github.repository == 'wireapp/cells-sdk-kmp'

    steps:
#      - name: Verify environment
#        run: |
#          echo "Environment variable SIGN_ARTIFACTS: ${{ vars.SIGN_ARTIFACTS }}"
#          echo "Environment variable TEST_VAR: ${{ vars.TEST_VAR }}"
#          echo " Test echo secret var: ${{ secrets.SONATYPE_USERNAME }}"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

#      - name: Setup Android SDK
#        uses: android-actions/setup-android@v3
#      - name: Set version for tag
#        run: |
#          echo "ORG_GRADLE_PROJECT_VERSION_NAME=${{ github.ref_name }}" >> $GITHUB_ENV

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      # Simply add the expected local.properties file
      - name: Configure Gradle
        run: touch ./local.properties

      - name: Verify JS
        run: ./gradlew compileKotlinJs

#      - name: Publish
#        run: ./gradlew publishToMavenLocal
#        env:
#          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_USERNAME }}
#          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_PWD }}
#          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PWD }}
#          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_KEY }}
##          BASE64_PGP_KEY: ${{ secrets.BASE64_PGP_KEY }}
#          SIGN_ARTIFACTS:  ${{ vars.SIGN_ARTIFACTS }}

      - name: Publish
        run: ./gradlew publishAndReleaseToMavenCentral
        env:
          SIGN_ARTIFACTS:  ${{ vars.SIGN_ARTIFACTS }}
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_PWD }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PWD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_KEY }}
